<?php

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0-SNAPSHOT
 */

namespace winwin\eventBus\client;

use wenbinye\tars\protocol\annotation\TarsProperty;

final class Notification
{
    /**
     * @TarsProperty(order = 0, required = true, type = "string")
     *
     * @var string
     */
    public $createTime;

    /**
     * @TarsProperty(order = 1, required = true, type = "string")
     *
     * @var string
     */
    public $eventId;

    /**
     * @TarsProperty(order = 2, required = true, type = "string")
     *
     * @var string
     */
    public $topic;

    /**
     * @TarsProperty(order = 3, required = true, type = "string")
     *
     * @var string
     */
    public $eventName;

    /**
     * @TarsProperty(order = 4, required = true, type = "string")
     *
     * @var string
     */
    public $payload;
}
